/**
*** Ashim Ghimire - Prog Lang/Compilers CS4223 Spring 2011
*** Driver to test the automatic scanner generated by Lex.
*** file created by lex: lex.yy.c 
*** yylex() scanner function
*** yytext token string
**/

#include <iostream>
#include <iomanip>
#include "lex.yy.c"
using namespace std;

int main()
{
while(true)
{
int code = yylex(); // Get a token and
cout << setw(15) << left << yytext // display it.
<< '\t' << code << endl;
}
}

/*************************************************************/
int yywrap()
{
// This function is called by the scanner at the end of file.
cout << "EOF \n";
exit(0); // Terminate the program.
}
